# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='id_projet',
            field=models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='projet.Projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id_category',
            field=models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='projet.Categorie'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categorie',
        ),
        migrations.AlterModelTable(
            name='media',
            table='media',
        ),
        migrations.AlterModelTable(
            name='projet',
            table='projet',
        ),
    ]
