# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0002_projet_statut'),
        ('utilisateur', '0002_auto_20171110_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=30)),
                ('montant', models.DecimalField(decimal_places=13, max_digits=17)),
                ('Date', models.DateField()),
                ('Type_payement', models.CharField(choices=[('1', 'Joni joni'), ('2', 'Orange Money')], default='1', max_length=255)),
                ('id_projet', models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='projet.Projet')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
        ),
    ]
